# Generated by Django 4.1.7 on 2023-02-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcinfo',
            name='wi1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
