# Generated by Django 4.1.7 on 2023-02-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_arcinfo_wi1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arcinfo',
            name='wi1',
        ),
    ]
