# Generated by Django 4.1.7 on 2023-02-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_arcinfo_wi1'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcinfo',
            name='wi1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='arcinfo',
            name='wi2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='arcinfo',
            name='wi3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='arcinfo',
            name='wi4',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='arcinfo',
            name='wi5',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='arcinfo',
            name='wi6',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
