# Generated by Django 4.1.7 on 2023-02-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_arcinfo_wi1_arcinfo_wi2_arcinfo_wi3_arcinfo_wi4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcinfo',
            name='wi1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='arcinfo',
            name='wi2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='arcinfo',
            name='wi3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='arcinfo',
            name='wi4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='arcinfo',
            name='wi5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='arcinfo',
            name='wi6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
