# Generated by Django 4.1.7 on 2023-02-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_arcinfo_wi1_alter_arcinfo_wi2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcinfo',
            name='wi6',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
