# Generated by Django 4.1.7 on 2023-02-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_arcinfo_wi6'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcinfo',
            name='title',
            field=models.CharField(blank=True, help_text='Enter an image title', max_length=100, null=True),
        ),
    ]
