# Generated by Django 4.1.7 on 2023-02-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_arcinfo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arcinfo',
            name='wi2',
        ),
        migrations.RemoveField(
            model_name='arcinfo',
            name='wi3',
        ),
        migrations.RemoveField(
            model_name='arcinfo',
            name='wi4',
        ),
        migrations.RemoveField(
            model_name='arcinfo',
            name='wi5',
        ),
        migrations.RemoveField(
            model_name='arcinfo',
            name='wi6',
        ),
    ]
