# Generated by Django 4.1.7 on 2023-02-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_arcinfo_wi2_remove_arcinfo_wi3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('title', models.CharField(help_text='Enter an image title', max_length=100, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='arcinfo',
            name='title',
        ),
        migrations.AddField(
            model_name='arcinfo',
            name='wi2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='arcinfo',
            name='wi3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='arcinfo',
            name='wi4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='arcinfo',
            name='wi5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='arcinfo',
            name='wi6',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
