# Generated by Django 4.1.7 on 2023-02-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_arcinfo_wi6'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
        migrations.AddField(
            model_name='equipinfo',
            name='ch',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
