# Generated by Django 4.1.7 on 2023-02-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_deviceinfo_empinfo_estabinfo_facilitiesinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitiesinfo',
            name='mosqpic',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='your image'),
        ),
    ]
