# Generated by Django 4.1.7 on 2023-02-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_facilitiesinfo_mosqpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitiesinfo',
            name='mosqpic',
            field=models.ImageField(blank=True, help_text='your image', null=True, upload_to='images/'),
        ),
    ]
