# Generated by Django 4.1.7 on 2023-02-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_facilitiesinfo_mosqpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcinfo',
            name='wi1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Workshop Image1'),
        ),
        migrations.AlterField(
            model_name='arcinfo',
            name='wi2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Workshop Image2'),
        ),
        migrations.AlterField(
            model_name='arcinfo',
            name='wi3',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Workshop Image3'),
        ),
        migrations.AlterField(
            model_name='arcinfo',
            name='wi4',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Workshop Image4'),
        ),
        migrations.AlterField(
            model_name='arcinfo',
            name='wi5',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Workshop Image5'),
        ),
        migrations.AlterField(
            model_name='arcinfo',
            name='wi6',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Workshop Image6'),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='cards',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Use of personal identification cards pic/ تعليق البطاقات التعريفية.'),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='uniform',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='All employees wearing a uniform pic/ارتداء العاملين زي رسمي موحد'),
        ),
        migrations.AlterField(
            model_name='estabinfo',
            name='areapic',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Private and shaded parking areas picture./مواقف خاصة ومظللة'),
        ),
        migrations.AlterField(
            model_name='estabinfo',
            name='certi',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='place the classification certificate at the entrance picture./تثبيت شهادة التصنيف حسب التعليمات عند المدخل.'),
        ),
        migrations.AlterField(
            model_name='estabinfo',
            name='comm',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Commercial Registration/التسجيل التجاري'),
        ),
        migrations.AlterField(
            model_name='estabinfo',
            name='defec',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Nameplate Picture for no defects / لوحة اسم الصورة لعدم وجود عيوب'),
        ),
        migrations.AlterField(
            model_name='estabinfo',
            name='disab',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Provide ramps for services of persons with disabilities (according to comprehensive access guide instructions picture./توفير منحدرات لخدمة الأشخاص ذوي الإعاقة (حسب تعليمات دليل الوصول الشامل).'),
        ),
        migrations.AlterField(
            model_name='estabinfo',
            name='entrance',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Entrance Picture / صورة المدخل'),
        ),
        migrations.AlterField(
            model_name='estabinfo',
            name='exi',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Exit Picture / خروج من الصورة'),
        ),
        migrations.AlterField(
            model_name='estabinfo',
            name='lightpic',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='availability of suitable light around the establishment picture /توفر إضاءة مناسبة حول المنشأة.'),
        ),
        migrations.AlterField(
            model_name='estabinfo',
            name='mainroad',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Accessibility Main Road Picture/إمكانية الوصول إلى صورة الطريق الرئيسية'),
        ),
        migrations.AlterField(
            model_name='estabinfo',
            name='munci',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Municipality License/رخصة البلدية'),
        ),
        migrations.AlterField(
            model_name='estabinfo',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Accessibility from Sub Road Picture'),
        ),
        migrations.AlterField(
            model_name='estabinfo',
            name='platepic',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='NamePlate Picture / صورة اللوحة'),
        ),
        migrations.AlterField(
            model_name='estabinfo',
            name='vat',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='VAT Certificate/شهادة ضريبة القيمة المضافة'),
        ),
        migrations.AlterField(
            model_name='facilitiesinfo',
            name='femalepic',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Two clean and in good condition toilets for customers; one for male and the other for females pic/ دورتي مياه نظيفة وبحالة جيدة، على أن تكون مخصَّصة للعملاء، إحداهما مخصصة للرجال والأخرى للنساء '),
        ),
        migrations.AlterField(
            model_name='facilitiesinfo',
            name='mosqpic',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Provide a special area for praying in case there is no near mosque pic/توفير مساحة خاصة للصلاة عند عدم وجود مسجد قريب'),
        ),
        migrations.AlterField(
            model_name='facilitiesinfo',
            name='parka2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Provide parking areas for vehicles before or after repair process that shall be shaded and fenced pic/ مواقف ضمن حدود المنشأة لصف المركبات قبل أو بعد عملية الاصلاح ، على أن تكون مضللة ومسورة .'),
        ),
        migrations.AlterField(
            model_name='recepinfo',
            name='r11',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Place the guarantee policy clearly pic/ تثبيت سياسة الضمان بشكل واضح.'),
        ),
        migrations.AlterField(
            model_name='recepinfo',
            name='r13',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Place the communication number for complaints pic/ تثبيت رقم للتواصل عند وجود شكوى.'),
        ),
        migrations.AlterField(
            model_name='recepinfo',
            name='r15',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Provide special offices for receiving and delivering vehicles pic/ وجود مكاتب خاصة باستلام المركبات وأخرى خاصة بالتسليم.'),
        ),
        migrations.AlterField(
            model_name='recepinfo',
            name='r17',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Reception area should be in a good condition pic/ أن تكون مكاتب الاستقبال بحالة جيدة ومتناسقة.'),
        ),
        migrations.AlterField(
            model_name='recepinfo',
            name='r19',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Provide a suitable number of seats in a good condition for waiting customers pic/وجود مقاعد متناسقة لانتظار العملاء بعدد كافٍ وبحالة جيدة.'),
        ),
        migrations.AlterField(
            model_name='recepinfo',
            name='r4',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Provide reception area separate from workshop provided with new suitable furniture pic./وجود منطقة استقبال مفصولة عن الورشة مزوَّدة بأثاث جيد ومتناسق ، مع خلو الجدران والاسقف والأرضيات من العيوب .'),
        ),
        migrations.AlterField(
            model_name='recepinfo',
            name='r6',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Provide waiting areas for women only pic/وجود منطقة مخصصة لانتظار النساء.'),
        ),
        migrations.AlterField(
            model_name='recepinfo',
            name='r9',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Place all operation licenses and classification certificates clearly and according to instructions pic/ تثبيت جميع رخص التشغيل وشهادة التصنيف بشكل واضح وحسب التعليمات '),
        ),
    ]
