from django.db import models

# Create your models here.
from django.db import models
import uuid

# Create your models here.

class arcinfo(models.Model):
    company = models.CharField(max_length=200, null=True, blank=True)
    owner = models.CharField(max_length=200, null=True, blank=True)
    contact = models.CharField(max_length=200, null=True, blank=True)
    manager = models.CharField(max_length=200, null=True, blank=True)
    managercont = models.CharField(max_length=200, null=True, blank=True)
    estimate = models.CharField(max_length=200, null=True, blank=True)
    wi1 = models.ImageField(upload_to='images/',null=True, blank=True,verbose_name='Workshop Image1')
    wi2 = models.ImageField(upload_to='images/',null=True, blank=True,verbose_name='Workshop Image2')
    wi3 = models.ImageField(upload_to='images/',null=True, blank=True,verbose_name='Workshop Image3')
    wi4 = models.ImageField(upload_to='images/',null=True, blank=True,verbose_name='Workshop Image4')
    wi5 = models.ImageField(upload_to='images/',null=True, blank=True,verbose_name='Workshop Image5')
    wi6 = models.ImageField(upload_to='images/',null=True, blank=True,verbose_name='Workshop Image6')

class arcloc(models.Model):
    address = models.CharField(max_length=200, null=True, blank=True)

class financial(models.Model):
    labor = models.CharField(max_length=200, null=True, blank=True)
    part = models.CharField(max_length=200, null=True, blank=True)
    material = models.CharField(max_length=200, null=True, blank=True)
    rent = models.CharField(max_length=200, null=True, blank=True)
    productive = models.CharField(max_length=200, null=True, blank=True)
    support = models.CharField(max_length=200, null=True, blank=True)
    month = models.CharField(max_length=200, null=True, blank=True)

class workforceinfo(models.Model):
    PPE = models.CharField(max_length=200, null=True, blank=True)
    denter = models.CharField(max_length=200, null=True, blank=True)
    painter = models.CharField(max_length=200, null=True, blank=True)
    elec = models.CharField(max_length=200, null=True, blank=True)
    staff = models.CharField(max_length=200, null=True, blank=True)
    workbays = models.CharField(max_length=200, null=True, blank=True)
    body = models.CharField(max_length=200, null=True, blank=True)
    nonbody = models.CharField(max_length=200, null=True, blank=True)
    sqm = models.CharField(max_length=200, null=True, blank=True)
    insurance = models.CharField(max_length=200, null=True, blank=True)
    walkin = models.CharField(max_length=200, null=True, blank=True)
    fleet = models.CharField(max_length=200, null=True, blank=True)
    park = models.CharField(max_length=200, null=True, blank=True)
    recep = models.CharField(max_length=200, null=True, blank=True)
    wash = models.CharField(max_length=200, null=True, blank=True)
    washstaff = models.CharField(max_length=200, null=True, blank=True)
    scrap = models.CharField(max_length=200, null=True, blank=True)
    newpart = models.CharField(max_length=200, null=True, blank=True)
    oilstorage = models.CharField(max_length=200, null=True, blank=True)

class repairinfo(models.Model):
    measure = models.CharField(max_length=200, null=True, blank=True)
    nonstruct = models.CharField(max_length=200, null=True, blank=True)
    struct = models.CharField(max_length=200, null=True, blank=True)
    paint = models.CharField(max_length=200, null=True, blank=True)
    ac = models.CharField(max_length=200, null=True, blank=True)
    body = models.CharField(max_length=200, null=True, blank=True)
    qc = models.CharField(max_length=200, null=True, blank=True)
    brakes = models.CharField(max_length=200, null=True, blank=True)
    tyre = models.CharField(max_length=200, null=True, blank=True)
    wheel = models.CharField(max_length=200, null=True, blank=True)
    computer = models.CharField(max_length=200, null=True, blank=True)
    adas = models.CharField(max_length=200, null=True, blank=True)
    engine = models.CharField(max_length=200, null=True, blank=True)
    plastic = models.CharField(max_length=200, null=True, blank=True)
    welder = models.CharField(max_length=200, null=True, blank=True)

class equipinfo(models.Model):
    it = models.CharField(max_length=200, null=True, blank=True)
    comp = models.CharField(max_length=200, null=True, blank=True)
    access = models.CharField(max_length=200, null=True, blank=True)
    oem = models.CharField(max_length=200, null=True, blank=True)
    guide = models.CharField(max_length=200, null=True, blank=True)
    lift = models.CharField(max_length=200, null=True, blank=True)
    frame = models.CharField(max_length=200, null=True, blank=True)
    four = models.CharField(max_length=200, null=True, blank=True)
    anchor = models.CharField(max_length=200, null=True, blank=True)
    ton = models.CharField(max_length=200, null=True, blank=True)
    oxy = models.CharField(max_length=200, null=True, blank=True)
    resistance = models.CharField(max_length=200, null=True, blank=True)
    heater = models.CharField(max_length=200, null=True, blank=True)
    plasma = models.CharField(max_length=200, null=True, blank=True)
    mig = models.CharField(max_length=200, null=True, blank=True)
    dent = models.CharField(max_length=200, null=True, blank=True)
    air = models.CharField(max_length=200, null=True, blank=True)
    chain = models.CharField(max_length=200, null=True, blank=True)
    charging = models.CharField(max_length=200, null=True, blank=True)
    kit = models.CharField(max_length=200, null=True, blank=True)
    dry = models.CharField(max_length=200, null=True, blank=True)
    hvlp = models.CharField(max_length=200, null=True, blank=True)
    vet = models.CharField(max_length=200, null=True, blank=True)
    booth = models.CharField(max_length=200, null=True, blank=True)
    prep = models.CharField(max_length=200, null=True, blank=True)
    mixing = models.CharField(max_length=200, null=True, blank=True)
    tools = models.CharField(max_length=200, null=True, blank=True)
    toolkit = models.CharField(max_length=200, null=True, blank=True)
    lifts = models.CharField(max_length=200, null=True, blank=True)
    align = models.CharField(max_length=200, null=True, blank=True)
    rise = models.CharField(max_length=200, null=True, blank=True)
    changer = models.CharField(max_length=200, null=True, blank=True)
    balancer = models.CharField(max_length=200, null=True, blank=True)
    lathe = models.CharField(max_length=200, null=True, blank=True)
    notes = models.CharField(max_length=200, null=True, blank=True)

class estabinfo(models.Model):
    lice = models.CharField(max_length=200, null=True, blank=True)
    comm = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Commercial Registration/التسجيل التجاري')
    vat = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='VAT Certificate/شهادة ضريبة القيمة المضافة')
    munci = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Municipality License/رخصة البلدية')
    saso = models.CharField(max_length=200, null=True, blank=True)
    undertake = models.CharField(max_length=200, null=True, blank=True)
    access = models.CharField(max_length=200, null=True, blank=True)
    mainroad = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Accessibility Main Road Picture/إمكانية الوصول إلى صورة الطريق الرئيسية')
    subroad = models.CharField(max_length=200, null=True, blank=True)
    pic = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Accessibility from Sub Road Picture')
    exits = models.CharField(max_length=200, null=True, blank=True)
    entrance = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Entrance Picture / صورة المدخل')
    exi = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Exit Picture / خروج من الصورة')
    plate = models.CharField(max_length=200, null=True, blank=True)
    platepic = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='NamePlate Picture / صورة اللوحة')
    harmo = models.CharField(max_length=200, null=True, blank=True)
    defec = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Nameplate Picture for no defects / لوحة اسم الصورة لعدم وجود عيوب')
    light = models.CharField(max_length=200, null=True, blank=True)
    lightpic = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='availability of suitable light around the establishment picture /توفر إضاءة مناسبة حول المنشأة.')
    area = models.CharField(max_length=200, null=True, blank=True)
    areapic = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Private and shaded parking areas picture./مواقف خاصة ومظللة')
    place = models.CharField(max_length=200, null=True, blank=True)
    certi = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='place the classification certificate at the entrance picture./تثبيت شهادة التصنيف حسب التعليمات عند المدخل.')
    ramps = models.CharField(max_length=200, null=True, blank=True)
    disab = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Provide ramps for services of persons with disabilities (according to comprehensive access guide instructions picture./توفير منحدرات لخدمة الأشخاص ذوي الإعاقة (حسب تعليمات دليل الوصول الشامل).')

class recepinfo(models.Model):
    r1 = models.CharField(max_length=200, null=True, blank=True)
    r2 = models.CharField(max_length=200, null=True, blank=True)
    r3 = models.CharField(max_length=200, null=True, blank=True)
    r4 = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Provide reception area separate from workshop provided with new suitable furniture pic./وجود منطقة استقبال مفصولة عن الورشة مزوَّدة بأثاث جيد ومتناسق ، مع خلو الجدران والاسقف والأرضيات من العيوب .')
    r5 = models.CharField(max_length=200, null=True, blank=True)
    r6 = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Provide waiting areas for women only pic/وجود منطقة مخصصة لانتظار النساء.')
    r7 = models.CharField(max_length=200, null=True, blank=True)
    r8 = models.CharField(max_length=200, null=True, blank=True)
    r9 = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Place all operation licenses and classification certificates clearly and according to instructions pic/ تثبيت جميع رخص التشغيل وشهادة التصنيف بشكل واضح وحسب التعليمات ')
    r10 = models.CharField(max_length=200, null=True, blank=True)
    r11 = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Place the guarantee policy clearly pic/ تثبيت سياسة الضمان بشكل واضح.')
    r12 = models.CharField(max_length=200, null=True, blank=True)
    r13 = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Place the communication number for complaints pic/ تثبيت رقم للتواصل عند وجود شكوى.')
    r14 = models.CharField(max_length=200, null=True, blank=True)
    r15 = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Provide special offices for receiving and delivering vehicles pic/ وجود مكاتب خاصة باستلام المركبات وأخرى خاصة بالتسليم.')
    r16 = models.CharField(max_length=200, null=True, blank=True)
    r17 = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Reception area should be in a good condition pic/ أن تكون مكاتب الاستقبال بحالة جيدة ومتناسقة.')
    r18 = models.CharField(max_length=200, null=True, blank=True)
    r19 = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Provide a suitable number of seats in a good condition for waiting customers pic/وجود مقاعد متناسقة لانتظار العملاء بعدد كافٍ وبحالة جيدة.')
    r20 = models.CharField(max_length=200, null=True, blank=True)
    r21 = models.CharField(max_length=200, null=True, blank=True)

class empinfo(models.Model):
    EPPE = models.CharField(max_length=200, null=True, blank=True)
    all = models.CharField(max_length=200, null=True, blank=True)
    uniform = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='All employees wearing a uniform pic/ارتداء العاملين زي رسمي موحد')
    use = models.CharField(max_length=200, null=True, blank=True)
    cards = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Use of personal identification cards pic/ تعليق البطاقات التعريفية.')
    speak = models.CharField(max_length=200, null=True, blank=True)
    aid = models.CharField(max_length=200, null=True, blank=True)
    one = models.CharField(max_length=200, null=True, blank=True)
    highly = models.CharField(max_length=200, null=True, blank=True)
    proof = models.CharField(max_length=200, null=True, blank=True)
    job = models.CharField(max_length=200, null=True, blank=True)
    repair = models.CharField(max_length=200, null=True, blank=True)


class servicesinfo(models.Model):
    website = models.CharField(max_length=200, null=True, blank=True)
    telephone = models.CharField(max_length=200, null=True, blank=True)
    appointment = models.CharField(max_length=200, null=True, blank=True)
    record = models.CharField(max_length=200, null=True, blank=True)
    system = models.CharField(max_length=200, null=True, blank=True)
    shall = models.CharField(max_length=200, null=True, blank=True)
    access = models.CharField(max_length=200, null=True, blank=True)
    cost = models.CharField(max_length=200, null=True, blank=True)
    wash = models.CharField(max_length=200, null=True, blank=True)
    sama = models.CharField(max_length=200, null=True, blank=True)
    credit = models.CharField(max_length=200, null=True, blank=True)


class facilitiesinfo(models.Model):
    parka1 = models.CharField(max_length=200, null=True, blank=True)
    parka2 = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Provide parking areas for vehicles before or after repair process that shall be shaded and fenced pic/ مواقف ضمن حدود المنشأة لصف المركبات قبل أو بعد عملية الاصلاح ، على أن تكون مضللة ومسورة .')
    female = models.CharField(max_length=200, null=True, blank=True)
    femalepic = models.ImageField(upload_to='images/', null=True, blank=True,verbose_name='Two clean and in good condition toilets for customers; one for male and the other for females pic/ دورتي مياه نظيفة وبحالة جيدة، على أن تكون مخصَّصة للعملاء، إحداهما مخصصة للرجال والأخرى للنساء ')
    mosq = models.CharField(max_length=200, null=True, blank=True)
    mosqpic = models.ImageField(upload_to='images/', null=True, blank=True, verbose_name="Provide a special area for praying in case there is no near mosque pic/توفير مساحة خاصة للصلاة عند عدم وجود مسجد قريب")
    risk = models.CharField(max_length=200, null=True, blank=True)


class deviceinfo(models.Model):
    calibrate = models.CharField(max_length=200, null=True, blank=True)
    inspect = models.CharField(max_length=200, null=True, blank=True)
    provide = models.CharField(max_length=200, null=True, blank=True)